import bindless;
import types;

public static const Tex2D<f32> SHADOW_ID = 0u;
public static const Tex3D<Vec3> TONY_MC_MAPFACE_ID = 1u;
public static const Tex2D DFG_ID = 2u;
public static const TexCube ENVIRONMENT_MAP_ID = 3u;

public static const Sampler DEFAULT_SAMPLER_ID = 0u;
public static const SamplerComparison SHADOW_SAMPLER_ID = 1u;
public static const Sampler ENVIRONMENT_SAMPLER_ID = 2u;

public static const RWTex2D RESOLVED_IMAGE_ID = 0u;
